services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile  # Only include this if you renamed it from just "Dockerfile"
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  emulator:
    build:
      context: ./backend/emulator
      dockerfile: emulator.Dockerfile
    container_name: sensors-emulator
    depends_on:
      - backend
